use_frameworks!

platform :ios, '13.0'

target 'IncidenceLibraryIOS_Example' do
  pod 'IncidenceLibraryIOS', :path => '../'

  target 'IncidenceLibraryIOS_Tests' do
    inherit! :search_paths

    
  end
end
